config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root 'products#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  include Paperclip::Glue
  has_attached_file :image, style: { medium: "300x300>", thumb: "100x100>" }, default_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/300px-No_image_available.svg.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, :description, :price, presence: true
  validates_numericality_of :price, greater_than: 0
  validate :title_is_shorter_than_description



  before_save :strip_html_description, :to_lower_case_title
  belongs_to :category, optional: false

  def strip_html_description
    self.description = ActionView::Base.full_sanitizer.sanitize(self.description)
  end

  def to_lower_case_title
    self.title = title.downcase
  end

  def title_is_shorter_than_description
    return if title.blank? or description.blank?
    return errors.add(:description, 'cant be shorter than title') if description.length < title.length
    # if title.length > description.length
    #   errors.add(:description, 'cant be shorter than title')
    # end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :getProduct, only: [:show, :edit, :update, :destroy]
  before_action :product_params, only: [:create, :update]
  def index
    @products = Product.all
  end

  def show
    # byebug
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    return redirect_to products_url, notice: 'You have sucessfully created the product' if @product.save
    flash[:alert] = "Error in form 2"
    render :new
  end

  def edit
  end

  def update
    return redirect_to products_url, notice: 'Update sucessfully' if @product.update(product_params)
    flash[:alert] = 'Update fail'
    render :new
  end

  def destroy
    return redirect_to products_url, notice: 'Delete sucessfully' if @product.destroy
      redirect_to products_path, alert: 'Delete failed'
  end

  private
    def getProduct
      @product = Product.find(params[:id])
    end

    def product_params
      product_params = params.require(:product).permit( :title,
                                                  :description,
                                                  :price,
                                                  :published,
                                                  :category_id,
                                                  :country,
                                                  :level,
                                                  :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tddrails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DemoTddrails
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    -if flash[:notice]
      =flash[:notice]
      
    p.notice = notice
    p.alert = alert
    = yield

app/views/products/_form.slim
= semantic_form_for @product do |f|
  = f.input :title
  = f.input :description
  = f.input :price, min: 1
  = f.input :category
  = f.file_field :image
  = f.submit :submit

app/views/products/_product.html.slim
tr
  td = product.title
  td = product.category.try(:title)
  td = link_to 'Readmore', product_path(product)
  td
    span.edit
      = link_to 'Edit', edit_product_path(product)
  td = link_to 'Delete', product_path(product), method: :delete, data:  {confirm: 'Are you want to delete this product?'}

app/views/products/create.html.slim
h1
  | Products#create
p
  | Find me in app/views/products/create.html.erb

app/views/products/edit.slim
h1
  | Products#edit
= render 'form'

app/views/products/index.slim
h1 Products#index
p Find me in app/views/products/index.html.erb
= link_to 'Create', new_product_path
table
  tr
    th Product Title
    th Category
    th Readmore
    th Edit
    th Delete
    = render partial: 'product', collection: @products

app/views/products/new.html.slim
h1
  | Products#new
p
  | Find me in app/views/products/new.html.erb

= render 'form'

app/views/products/show.html.slim
h1
  | Products#show
p
  | Find me in app/views/products/show.html.erb
table
  tr
    th
      | Product Title
    th
      | Category
    th
      | Price
    th
      | Image
    / th
    /   | Level
    / th
      | Published
  tr
    td
      = @product.title
    td
      = @product.category.try(:title)
    td
      = @product.price
    td
      / img{ src =@product.image.url{:thumb} }
      = image_tag @product.image.url
      / = image_tag @product.image.url(:thumb)
      / = image_tag @product.image.url(:medium)

    = link_to 'edit', edit_product_path
    = link_to 'delete', product_path(@product)